"""empty message

Revision ID: 6f62aa75b671
Revises: 4018c733a8fb
Create Date: 2025-11-08 23:51:55.563879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f62aa75b671'
down_revision: Union[str, None] = '4018c733a8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(
        sa.text(
            """
            UPDATE shop
            SET sector = CASE sector
                WHEN 'Markaziy' THEN '101'
                WHEN 'Yangi shahar' THEN '203'
                WHEN 'Eski shahar' THEN '305'
                WHEN 'Industrial' THEN '420'
                ELSE COALESCE(NULLIF(regexp_replace(sector, '\\D', '', 'g'), ''), '0')
            END,
            number = COALESCE(NULLIF(regexp_replace(number, '\\D', '', 'g'), ''), '0')
            """
        )
    )

    op.alter_column(
        'shop',
        'sector',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using="sector::integer"
    )
    op.alter_column(
        'shop',
        'number',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        postgresql_using="number::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop', 'number',
                existing_type=sa.Integer(),
                type_=sa.VARCHAR(),
                existing_nullable=False)
    op.alter_column('shop', 'sector',
                existing_type=sa.Integer(),
                type_=sa.VARCHAR(),
                existing_nullable=False)
    # ### end Alembic commands ###